from __future__ import annotations

from sim2real.config.robots.base import PROJECT_ROOT, RobotCfg


G1_CFG = RobotCfg(
    name="g1",
    robot_type="g1_29dof",
    joint_names=(
        "left_hip_pitch_joint",
        "left_hip_roll_joint",
        "left_hip_yaw_joint",
        "left_knee_joint",
        "left_ankle_pitch_joint",
        "left_ankle_roll_joint",
        "right_hip_pitch_joint",
        "right_hip_roll_joint",
        "right_hip_yaw_joint",
        "right_knee_joint",
        "right_ankle_pitch_joint",
        "right_ankle_roll_joint",
        "waist_yaw_joint",
        "waist_roll_joint",
        "waist_pitch_joint",
        "left_shoulder_pitch_joint",
        "left_shoulder_roll_joint",
        "left_shoulder_yaw_joint",
        "left_elbow_joint",
        "left_wrist_roll_joint",
        "left_wrist_pitch_joint",
        "left_wrist_yaw_joint",
        "right_shoulder_pitch_joint",
        "right_shoulder_roll_joint",
        "right_shoulder_yaw_joint",
        "right_elbow_joint",
        "right_wrist_roll_joint",
        "right_wrist_pitch_joint",
        "right_wrist_yaw_joint",
    ),
    body_names=(
        "pelvis",
        "left_hip_pitch_link",
        "left_hip_roll_link",
        "left_hip_yaw_link",
        "left_knee_link",
        "left_ankle_pitch_link",
        "left_ankle_roll_link",
        "left_toe_link",
        "pelvis_contour_link",
        "right_hip_pitch_link",
        "right_hip_roll_link",
        "right_hip_yaw_link",
        "right_knee_link",
        "right_ankle_pitch_link",
        "right_ankle_roll_link",
        "right_toe_link",
        "waist_yaw_link",
        "waist_roll_link",
        "torso_link",
        "head_link",
        "head_mocap",
        "imu_in_torso",
        "left_shoulder_pitch_link",
        "left_shoulder_roll_link",
        "left_shoulder_yaw_link",
        "left_elbow_link",
        "left_wrist_roll_link",
        "left_wrist_pitch_link",
        "left_wrist_yaw_link",
        "left_rubber_hand",
        "right_shoulder_pitch_link",
        "right_shoulder_roll_link",
        "right_shoulder_yaw_link",
        "right_elbow_link",
        "right_wrist_roll_link",
        "right_wrist_pitch_link",
        "right_wrist_yaw_link",
        "right_rubber_hand",
    ),
    joint_pos_lower_limit={
        "left_hip_pitch_joint": -2.5307,
        "right_hip_pitch_joint": -2.5307,
        "waist_yaw_joint": -2.6180,
        "waist_pitch_joint": -0.52,
        "waist_roll_joint": -0.52,
        "left_hip_roll_joint": -0.5236,
        "right_hip_roll_joint": -2.9671,
        "left_hip_yaw_joint": -2.7576,
        "right_hip_yaw_joint": -2.7576,
        "left_knee_joint": -0.0873,
        "right_knee_joint": -0.0873,
        "left_shoulder_pitch_joint": -3.0892,
        "right_shoulder_pitch_joint": -3.0892,
        "left_ankle_pitch_joint": -0.8727,
        "right_ankle_pitch_joint": -0.8727,
        "left_shoulder_roll_joint": -1.5882,
        "right_shoulder_roll_joint": -2.2515,
        "left_ankle_roll_joint": -0.2618,
        "right_ankle_roll_joint": -0.2618,
        "left_shoulder_yaw_joint": -2.6180,
        "right_shoulder_yaw_joint": -2.6180,
        "left_elbow_joint": -1.0472,
        "right_elbow_joint": -1.0472,
        "left_wrist_roll_joint": -1.9722,
        "right_wrist_roll_joint": -1.9722,
        "left_wrist_pitch_joint": -1.6144,
        "right_wrist_pitch_joint": -1.6144,
        "left_wrist_yaw_joint": -1.6144,
        "right_wrist_yaw_joint": -1.6144,
    },
    joint_pos_upper_limit={
        "left_hip_pitch_joint": 2.8798,
        "right_hip_pitch_joint": 2.8798,
        "waist_yaw_joint": 2.6180,
        "waist_pitch_joint": 0.52,
        "waist_roll_joint": 0.52,
        "left_hip_roll_joint": 2.9671,
        "right_hip_roll_joint": 0.5236,
        "left_hip_yaw_joint": 2.7576,
        "right_hip_yaw_joint": 2.7576,
        "left_knee_joint": 2.8798,
        "right_knee_joint": 2.8798,
        "left_shoulder_pitch_joint": 2.6704,
        "right_shoulder_pitch_joint": 2.6704,
        "left_ankle_pitch_joint": 0.5236,
        "right_ankle_pitch_joint": 0.5236,
        "left_shoulder_roll_joint": 2.2515,
        "right_shoulder_roll_joint": 1.5882,
        "left_ankle_roll_joint": 0.2618,
        "right_ankle_roll_joint": 0.2618,
        "left_shoulder_yaw_joint": 2.6180,
        "right_shoulder_yaw_joint": 2.6180,
        "left_elbow_joint": 2.0944,
        "right_elbow_joint": 2.0944,
        "left_wrist_roll_joint": 1.9722,
        "right_wrist_roll_joint": 1.9722,
        "left_wrist_pitch_joint": 1.6144,
        "right_wrist_pitch_joint": 1.6144,
        "left_wrist_yaw_joint": 1.6144,
        "right_wrist_yaw_joint": 1.6144,
    },
    joint_velocity_limit={
        "left_hip_pitch_joint": 32.0,
        "right_hip_pitch_joint": 32.0,
        "waist_yaw_joint": 32.0,
        "left_hip_roll_joint": 32.0,
        "right_hip_roll_joint": 32.0,
        "left_hip_yaw_joint": 32.0,
        "right_hip_yaw_joint": 32.0,
        "left_knee_joint": 20.0,
        "right_knee_joint": 20.0,
        "left_shoulder_pitch_joint": 37.0,
        "right_shoulder_pitch_joint": 37.0,
        "left_ankle_pitch_joint": 37.0,
        "right_ankle_pitch_joint": 37.0,
        "left_shoulder_roll_joint": 37.0,
        "right_shoulder_roll_joint": 37.0,
        "left_ankle_roll_joint": 37.0,
        "right_ankle_roll_joint": 37.0,
        "left_shoulder_yaw_joint": 37.0,
        "right_shoulder_yaw_joint": 37.0,
        "left_elbow_joint": 37.0,
        "right_elbow_joint": 37.0,
        "left_wrist_roll_joint": 37.0,
        "right_wrist_roll_joint": 37.0,
        "left_wrist_pitch_joint": 22.0,
        "right_wrist_pitch_joint": 22.0,
        "left_wrist_yaw_joint": 22.0,
        "right_wrist_yaw_joint": 22.0,
    },
    joint_effort_limit={
        "left_hip_pitch_joint": 88.0,
        "left_hip_roll_joint": 88.0,
        "left_hip_yaw_joint": 88.0,
        "left_knee_joint": 139.0,
        "left_ankle_pitch_joint": 50.0,
        "left_ankle_roll_joint": 50.0,
        "right_hip_pitch_joint": 88.0,
        "right_hip_roll_joint": 88.0,
        "right_hip_yaw_joint": 88.0,
        "right_knee_joint": 139.0,
        "right_ankle_pitch_joint": 50.0,
        "right_ankle_roll_joint": 50.0,
        "waist_yaw_joint": 88.0,
        "waist_roll_joint": 50.0,
        "waist_pitch_joint": 50.0,
        "left_shoulder_pitch_joint": 25.0,
        "left_shoulder_roll_joint": 25.0,
        "left_shoulder_yaw_joint": 25.0,
        "left_elbow_joint": 25.0,
        "left_wrist_roll_joint": 25.0,
        "left_wrist_pitch_joint": 5.0,
        "left_wrist_yaw_joint": 5.0,
        "right_shoulder_pitch_joint": 25.0,
        "right_shoulder_roll_joint": 25.0,
        "right_shoulder_yaw_joint": 25.0,
        "right_elbow_joint": 25.0,
        "right_wrist_roll_joint": 25.0,
        "right_wrist_pitch_joint": 5.0,
        "right_wrist_yaw_joint": 5.0,
    },
    mjcf_path=PROJECT_ROOT / "data" / "robots" / "g1" / "g1-mjlab.xml",
    sim_mjcf_path=PROJECT_ROOT / "data" / "robots" / "g1" / "g1-mjlab.xml",
    default_qpos=(
        0.0,
        0.0,
        0.8,
        1.0,
        0.0,
        0.0,
        0.0,
        -0.2,
        0.0,
        0.0,
        0.4,
        -0.2,
        0.0,
        -0.2,
        0.0,
        0.0,
        0.4,
        -0.2,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.4,
        0.0,
        1.2,
        0.0,
        0.0,
        0.0,
        0.0,
        -0.4,
        0.0,
        1.2,
        0.0,
        0.0,
        0.0,
    ),
    publish_hz=50.0,
    domain_id=0,
    interface="eth0",
    mocap_ip="localhost",
    use_joystick=False,
    viewer_track_body_names=("pelvis",),
    elastic_band_attach_body_names=("torso_link", "base_link"),
)
